name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
            target: wasm32-unknown-unknown
      - name: install tailwindind cli (ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run:
          wget -O tailwindcss "https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.2/tailwindcss-linux-x64" && chmod +x tailwindcss
      - name: install tailwindind cli (macos)
        if: matrix.platform == 'macos-latest'
        run:
          wget -O tailwindcss "https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.2/tailwindcss-macos-x64" && chmod +x tailwindcss
#      - name: install tailwindind cli (win)
#        if: matrix.platform == 'windows-latest'
#        run:
#          wget "https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.2/tailwindcss-windows-x64.exe" -O tailwindcss
#          chmod +x tailwindcss
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run:
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: rustup target add wasm32-unknown-unknown && cargo install --locked trunk
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
